### ISSUE TITLE
All systems operational in readme.md should be All systems are operational.

### ISSUE THREAD

**Issue by jasham** [EddieHubCommunity/monitoring#4]
**Describe the bug**
In readme.md file line which says All systems operational should be All systems are operational

**To Reproduce**
1. Go to ['...'](https://github.com/EddieHubCommunity/monitoring)
2. Scroll down a little and check in Readme.md file

**Expected behavior**
the sentence should be All systems are operational

**Comment by AshishG97** [comment]
Can you please assign this issue to me I have fixed this issue?
